# Generated by Django 5.1.3 on 2024-12-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='posts',
            name='artist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
