# Generated by Django 5.1.3 on 2024-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='artist',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
