# Generated by Django 5.1.3 on 2024-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_posts_artist_alter_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='sslug',
            new_name='slug',
        ),
    ]
